---
- name: Create deploy directory
  file:
    path: '{{ static_site_deploy_directory }}'
    state: directory
    # owner: ?
    # group: ?
    # mode: 0500

- name: Add index page
  template:
    src: index.html.j2
    dest: '{{ static_site_deploy_directory }}/index.html'

