---
- name: Create static website.
  hosts: localhost
  connection: local
  tasks:
   - name: Include all .yml files in the vars/static-site directory
     include_vars:
       dir: vars/static-site
       extensions: [yml]

   - name: Import create-static-site role
     import_role:
       name: create-static-site

